# Numpy Assignments

In [1]:
## Consider the below code to answer further questions:

import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

### Q1) Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
#### Ans) Yes there is different data type in both variables.

In [2]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


### Q2) Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
def test(x):
    print(x,type(x))
    for i in x:
        print(type(i),i)

In [4]:
test(list_)

['1', '2', '3', '4', '5'] <class 'list'>
<class 'str'> 1
<class 'str'> 2
<class 'str'> 3
<class 'str'> 4
<class 'str'> 5


In [5]:
test(array_list)

['1' '2' '3' '4' '5'] <class 'numpy.ndarray'>
<class 'numpy.str_'> 1
<class 'numpy.str_'> 2
<class 'numpy.str_'> 3
<class 'numpy.str_'> 4
<class 'numpy.str_'> 5


### Q3) Considering the following changes in the variable, array_list:
> array_list = np.array(object = list_, dtype = int)

##### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [6]:
array_list = np.array(object = list_, dtype = int)

In [7]:
test(list_)

['1', '2', '3', '4', '5'] <class 'list'>
<class 'str'> 1
<class 'str'> 2
<class 'str'> 3
<class 'str'> 4
<class 'str'> 5


In [8]:
test(array_list)

[1 2 3 4 5] <class 'numpy.ndarray'>
<class 'numpy.int64'> 1
<class 'numpy.int64'> 2
<class 'numpy.int64'> 3
<class 'numpy.int64'> 4
<class 'numpy.int64'> 5


In [9]:
array_list

array([1, 2, 3, 4, 5])

In [10]:
## Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4) Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size

In [11]:
print("* Shape:- ",np.shape(num_array))
print("* Size :- ",np.size(num_array))

* Shape:-  (2, 3)
* Size :-  6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
>[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6) Create an identity matrix of shape (5,5) using numpy functions?
>[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])